In [3]:
import numpy as np

In [3]:
>>> a = np.arange(6)
>>> a2 = a[np.newaxis, :]
>>> a2.shape

(1, 6)

In [11]:
a = np.array([1, 2, 3, 4, 5, 6])

In [13]:
 a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [15]:
print(a[0])


[1 2 3 4]


In [17]:
a = np.array([1, 2, 3])

In [19]:
np.zeros(2)

array([0., 0.])

In [21]:
np.ones(2)

array([1., 1.])

In [23]:
np.empty(2)


array([1., 1.])

In [5]:
np.arange(4)


array([0, 1, 2, 3])

In [9]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [11]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [17]:
#Adding, removing, and sorting elements

In [19]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
'''argsort, which is an indirect sort along a specified axi
lexsort, which is an indirect stable sort on multiple keys,
searchsorted, which will find elements in a sorted array, a
partition, which is a partial sort.'''

In [21]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
array_example = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],[[0 ,1 ,2, 3],[4, 5, 6, 7]]])
array_example.ndim

3

In [27]:
array_example.size

24

In [29]:
array_example.shape

(3, 2, 4)

In [31]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [33]:
b = a.reshape(3, 2)
print(b)


[[0 1]
 [2 3]
 [4 5]]


In [35]:
 np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [39]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [41]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [43]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [45]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [47]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [49]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [51]:
#Indexing and slicing

In [55]:
data = np.array([1, 2, 3])
data[1]

2

In [57]:
data[0:2]

array([1, 2])

In [59]:
data[1:]

array([2, 3])

In [61]:
data[-2:]

array([2, 3])

In [63]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [65]:
print(a[a < 5])

[1 2 3 4]


In [67]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [69]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [71]:
c = a[(a > 2) & (a < 11)]
print(c)


[ 3  4  5  6  7  8  9 10]


In [73]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [75]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [77]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [79]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
     print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [81]:
print(a[b])

[1 2 3 4]


In [83]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [85]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [87]:
arr1 = a[3:8]
arr1


array([4, 5, 6, 7, 8])

In [89]:
arr1 = a[3:8]
arr1


array([4, 5, 6, 7, 8])

In [91]:
a1 = np.array([[1, 1],[2, 2]])
a2 = np.array([[3, 3],[4, 4]])


In [93]:
 np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [95]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [97]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [99]:
 np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [103]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [105]:
 a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [107]:
b1 = a[0, :]
b1


array([1, 2, 3, 4])

In [109]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [111]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
 b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [117]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [119]:
data - ones

array([0, 1])

In [121]:
data * data

array([1, 4])

In [123]:
data / data

array([1., 1.])

In [127]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [135]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [137]:
b.sum(axis=1)

array([2, 4])

In [139]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [141]:
data.max()

2.0

In [143]:
 data.min()

1.0

In [145]:
data.sum()

3.0

In [155]:
 a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652], 
               [0.54627315, 0.05093587, 0.40067661, 0.55645993],
               [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [157]:
a.sum()

4.8595784

In [159]:
a.min()

0.05093587

In [163]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [165]:
#Creating matrices

In [167]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [169]:
data[0, 1]

2

In [171]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [177]:
data[0:2,1]

array([2, 4])

In [179]:
data.max()

6

In [181]:
data.min()

1

In [183]:
data.sum()

21

In [185]:
dta = np.array([[1,2],[5,3],[4,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [187]:
data.max(axis=0)

array([5, 6])

In [191]:
data.max(axis=1)

array([2, 4, 6])

In [193]:
data = np.array([[1,2],[3,4]])
ones = np.array([[1,1],[1,1]])
data+ones

array([[2, 3],
       [4, 5]])

In [21]:
data = np.array([[1,2],[3,4],[5,6]])
ones_row = np.array([[1,1]])
data+ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [199]:
np.ones((4, 3, 2))


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [201]:
np.ones(3)

array([1., 1., 1.])

In [203]:
np.zeros(3)

array([0., 0., 0.])

In [205]:
rng = np.random.default_rng()
rng.random(3)

array([0.0792348 , 0.05541161, 0.10654741])

In [207]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [209]:
 np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [211]:
rng.random((3, 2))

array([[0.14699236, 0.28258714],
       [0.39953137, 0.23986224],
       [0.16671933, 0.04188865]])

In [213]:
#Generating random numbers

In [215]:
rng.integers(5, size=(2, 4))

array([[4, 1, 4, 1],
       [0, 0, 1, 0]], dtype=int64)

In [217]:
#How to get unique items and counts

In [219]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [221]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [223]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [225]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [5]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [7]:
unique_values = np.unique(a_2d)
print(unique_values)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
unique_rows, indices, occurrence_count = np.unique( a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(indices)

[0 1 2]


In [15]:
print(occurrence_count)


[2 1 1]


In [17]:
#Transposing and reshaping a matrix

In [23]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [31]:
#How to reverse an array

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])


In [35]:
reversed_arr = np.flip(arr)

In [37]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [39]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [41]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [43]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)


[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [45]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [47]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)


[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [49]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [51]:
#Reshaping and flattening multidimensional arrays

In [53]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [55]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
a1 = x.flatten()
a1[0] = 99
print(x) # Original array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [59]:
#How to access the docstring for more information

In [61]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [63]:
In [0]: max?

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method

In [65]:
a = np.array([1, 2, 3, 4, 5, 6])

In [67]:
In [1]: a?

Type:        ndarray
String form: [1 2 3 4 5 6]
Length:      6
File:        c:\users\admin\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object 

In [71]:
def double(a):
    return a * 2


In [73]:
In [2]: double?


Signature: double(a)
Docstring: <no docstring>
File:      c:\users\admin\appdata\local\temp\ipykernel_7928\4163687287.py
Type:      function

In [75]:
In [3]: double??


Signature: double(a)
Docstring: <no docstring>
Source:   
def double(a):
#Return a * 2
    return a * 2
File:      c:\users\admin\appdata\local\temp\ipykernel_7928\4163687287.py
Type:      function

In [77]:
In [4]: len?


Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [79]:
In [5]: len??


Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [81]:
#How to save and load NumPy objects


In [83]:
a = np.array([1, 2, 3, 4, 5, 6])


In [85]:
np.save('filename', a)

In [87]:
b = np.load('filename.npy')

In [89]:
print(b)

[1 2 3 4 5 6]


In [91]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
np.savetxt('new_file.csv', csv_arr)

In [95]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])